name: Deploy to AWS Lambda & API Gateway
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-session-token: '${{secrets.AWS_SESSION_TOKEN}}'
          aws-region: me-south-1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies for layer
        run: |
          mkdir -p layer_dependencies/python/
          pip install -r layer_deps/requirements.txt -t layer_deps/python/
      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli
      - name: SAM Build
        run: sam build
      - name: SAM Deploy
        run: >-
          sam deploy --stack-name coveringSchedule-stack --capabilities
          CAPABILITY_IAM --no-confirm-changeset --resolve-s3
